name: aec22
channels:
    - conda-forge

dependencies:
   - python=3.9
   - pip
   - git
   - compas
   - compas_cgal
   - compas_occ
   - compas_view2
   - compas_fab
   - compas_rrc
   - pip:
     - ur-rtde
